{% set version = "2.3.7" %}

package:
  name: bob.extension
  version: {{ version }}

source:
  fn: bob.extension-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.extension/bob.extension-{{ version }}.zip
  md5: 9e30ad3d58f64c8f6b603d916c633f95

build:
  entry_points:
    - bob_new_version.py = bob.extension.scripts:new_version
    - bob_dependecy_graph.py = bob.extension.scripts:dependency_graph
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools

  run:
    - python
    - setuptools

test:
  requires:
    - nose
    - boost
    - cmake
    - pkg-config
    - freetype
    - libblitz
    - numpy
    - toolchain
    - sphinx_rtd_theme

  imports:
    - bob
    - bob.extension
    - bob.extension.scripts

  commands:
    - bob_new_version.py --help
    - bob_dependecy_graph.py --help
    - export CFLAGS="${CFLAGS} -pthread"  # [unix]
    - export LDFLAGS="${LDFLAGS} -lpthread"  # [unix]
    - nosetests -sv bob.extension  # [not osx]
    - DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib nosetests -sv bob.extension  # [osx]

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Building of Python/C++ extensions for Bob

extra:
  recipe-maintainers:
    - 183amir
